# This rule is not used by the project unstructured-data-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the operator.dataverse.redhat.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: sqsconsumer-editor-role
rules:
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - sqsconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - sqsconsumers/status
  verbs:
  - get
