apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
stringData:
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: LSIAQAAAAAAVNCBMPNSG
  AWS_SECRET_ACCESS_KEY: LSIAQAAAAAAVNCBMPNSG
  AWS_SESSION_TOKEN: LSIAQAAAAAAVNCBMPNSG
  AWS_ENDPOINT: http://localstack:4566
