## Append samples of your project ##
resources:
- operator_v1alpha1_controllerconfig.yaml
- operator_v1alpha1_sqsconsumer.yaml
- operator_v1alpha1_unstructureddataproduct.yaml
- operator_v1alpha1_documentprocessor.yaml
- operator_v1alpha1_chunksgenerator.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
