apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: ControllerConfig
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: controllerconfig
spec:
  awsSecret: aws-secret
  snowflakeConfig:
    name: "testing"
    account: "account-identifier"
    user: "SNOWFLAKE_USER"
    role: "TESTING_ROLE"
    region: "us-west-2"
    warehouse: "default"
    privateKeySecret: rhplatformtest-private-key
  unstructuredDataProcessingConfig:
    doclingServeURL: "http://localhost:5002"
    ingestionBucket: "data-ingestion-bucket"
    dataStorageBucket: "data-storage-bucket"
    cacheDirectory: "/tmp/cache/"
    maxConcurrentDoclingTasks: 5
    maxConcurrentLangchainTasks: 10
