apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: ControllerConfig
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: controllerconfig
spec:
  awsSecret: aws-secret
  snowflakeConfig:
    name: rhplatformtest
    account: "gdadclc-rhplatformtest"
    user: "shikgupt"
    role: "accountadmin"
    region: "us-west-2"
    warehouse: "default"
    defaultDatabase: "DB_DICE"
    privateKeySecret: rhplatformtest-private-key
  unstructuredDataProcessingConfig:
    doclingServeURL: "http://localhost:5001"
    ingestionBucket: "data-ingestion-bucket"
    dataStorageBucket: "data-storage-bucket"
    cacheDirectory: "/Users/shikgupt/Unstructured-Data-Initiative/unstructured-data-controller/tmp/cache/"
    maxConcurrentDoclingTasks: 5
    maxConcurrentLangchainTasks: 10
