apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: ControllerConfig
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: controllerconfig-sample
spec:
  awsSecret: aws-secret
  unstructuredDataProcessingConfig:
    ingestionBucket: data-ingestion-bucket
    dataStorageBucket: data-storage-bucket
    cacheDirectory: /Users/shikgupt/Unstructured-Data-Initiative/unstructured-data-controller/tmp/cache/