apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: ControllerConfig
metadata:
  labels:
    app.kubernetes.io/name: unstructured-data-controller
    app.kubernetes.io/managed-by: kustomize
  name: controllerconfig
spec:
  awsSecret: aws-secret
  unstructuredDataProcessingConfig:
    doclingServeURL: "http://localhost:5001"
    ingestionBucket: "data-ingestion-bucket"
    dataStorageBucket: "data-storage-bucket"
    cacheDirectory: "/home/ppunamiy/unstructured-data-controller/tmp/cache/"
    maxConcurrentDoclingTasks: 5
